# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 17:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
                ('last_login_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('register_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
